### ISSUE TITLE
Invalid C# when keyword in schema

### ISSUE THREAD

**Issue by RobJDavey** [Wish-Org/Wish.GraphQLSchemaGenerator#1]
Firstly, thank you for this project. I've found it to be a really nice lightweight way to generate classes compatible with System.Text.Json.

I recently came across an issue where an enum contained a C# keyword `in` which then resulted in an invalid file content.

``` GraphQL
enum DistanceEnum {
    # ...
    "Distance as Inches."
    in
    # ...
}
```

I manually updated the C# to `@in` which seems to also be compatible with `JsonStringEnumConverter<TEnum>`, so I think detecting keywords and just prefixing with `@` should hopefully not cause any issues.

**Comment by clement911** [comment]
Thanks for reporting this bug.
This is now fixed in the latest package Wish.GraphQLSchemaGenerator.1.5.5
